import { applications, availableUnits, residents, uuid, planFor } from "./data";
import { getMaintenance } from "./selectors";
import type { DemoState } from "./store";

// Fixed fictional identities link the sales story; they never authorize a real user.
export const demoStory = {
  unit: availableUnits.find((unit) => planFor(unit).bedrooms === 2)!,
  applicant: applications[0],
  resident: residents[0],
  maintenanceUserId: uuid(7, 102),
  leadId: uuid(17, 1000),
};
export function interestedUnit(state: DemoState) {
  return (
    availableUnits.find((unit) => unit.id === state.savedUnitId) ??
    demoStory.unit
  );
}
export function storyRequest(state: DemoState) {
  return getMaintenance(state).find(
    (request) =>
      state.tickets?.some((ticket) => ticket.id === request.id) &&
      state.requestDetails?.[request.id]?.attachments.some((file) =>
        file.mime.startsWith("image/"),
      ),
  );
}
export function storySteps(state: DemoState) {
  const request = storyRequest(state);
  const updated =
    !!request && ["in_progress", "completed"].includes(request.status);
  const visited = state.demoVisited ?? [];
  return [
    {
      id: "discover",
      title: "Find a two-bedroom home",
      description:
        "Explore The Mercer and choose an available apartment as Sofia.",
      href: "/demo/applicant",
      done: !!state.savedUnitId,
    },
    {
      id: "tour",
      title: "Request a tour",
      description:
        "Pick a day and time. The request appears in the manager’s leasing inbox.",
      href: "/demo/applicant/tour",
      done: !!state.tourDate,
    },
    {
      id: "apply",
      title: "Send a basic application",
      description:
        "Use fictional contact details; no screening or application fee.",
      href: "/demo/applicant/application",
      done: !!state.applicationSubmitted,
    },
    {
      id: "review",
      title: "Review it as the manager",
      description:
        "Find Sofia’s application and linked lead, with the same selected apartment.",
      href: "/demo/property-manager/applications",
      done: !!state.applicationSubmitted && visited.includes("manager-review"),
    },
    {
      id: "request",
      title: "Request a repair as Alex",
      description:
        "Add an image to a new resident request. A sample photo is ready to use.",
      href: "/demo/resident/maintenance/new",
      done: !!request,
    },
    {
      id: "assign",
      title: "Assign the repair",
      description:
        "Open the new request and assign Marcus Reed. Add a resident update if you like.",
      href: "/demo/property-manager/maintenance",
      done: request?.assigned_to === demoStory.maintenanceUserId,
    },
    {
      id: "work",
      title: "Start work as maintenance",
      description:
        "Marcus receives the assignment. Open it and choose Start work.",
      href: "/demo/maintenance",
      done: updated && request?.assigned_to === demoStory.maintenanceUserId,
    },
    {
      id: "resident-update",
      title: "See the resident update",
      description: "Alex’s request now shows the team’s progress and timeline.",
      href: request
        ? "/demo/resident/maintenance/" + request.id
        : "/demo/resident/maintenance",
      done: updated && visited.includes("resident-update"),
    },
    {
      id: "owner",
      title: "See the portfolio picture",
      description:
        "Finish with owner metrics and the activity generated by your demonstration.",
      href: "/demo/owner",
      done:
        updated &&
        visited.includes("resident-update") &&
        visited.includes("owner-overview"),
    },
  ];
}
